pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Source code checkout completed.'
            }
        }

        stage('Parallel Checks') {

            parallel {

                stage('Frontend Check') {
                    steps {
                        bat '"C:\\Users\\shrir\\AppData\\Local\\Programs\\Python\\Python312\\python.exe" project3-deploy/frontend_check.py'
                    }
                }

                stage('Backend Check') {
                    steps {
                        bat '"C:\\Users\\shrir\\AppData\\Local\\Programs\\Python\\Python312\\python.exe" project3-deploy/backend_check.py'
                    }
                }
            }
        }

        stage('Summary') {
            steps {
                echo 'Both frontend and backend checks are complete.'
            }
        }
    }
}
